#some good options in his config, but not to my tastes
configure_dotfiles: false
configure_terminal: false
configure_osx: false

#TODO some way of disabling system shortcuts that get in the way such as the ctrl-space shortcut in system prefs
#TODO some way of pinning packages, and ideally of stating version of packages we want (though that is tricky - brew seems to be a bit rubbish when it comes to getting old versions of packages)

configure_sudoers: false

homebrew_installed_packages:
  - act
  - aws-nuke
  - autoconf
  - bash-completion
  - bash-completion@2
  - bat
  - doxygen
  - dockutil
  - gettext
  - gifsicle
  - git
  - github/gh/gh
  - warrensbox/tap/tfswitch
  - go
  - gpg
  - fzf
  - httpie
  - iperf
  - libevent
  - sqlite
  - mcrypt
  - nmap
  - node
  - neofetch
  - nvm
  - ssh-copy-id
  - cowsay
  - readline
  - openssl
  - pv
  - telnet
  - wget
  - wrk
  - coreutils 
  - findutils 
  - gnu-tar 
  - gnu-sed 
  - gawk 
  - gnutls 
  - gnu-indent 
  - gnu-getopt 
  - grep
  - neovim
  - mtr
  - ripgrep
  - the_silver_searcher
  - speedtest-cli
  - leapp-cli
  - kubectx
  - tree
  - consul
  - yarn
  - yarn-completion
  - vault
  - helm
  - yamllint
  - jq
  - k9s
  - figlet
  - lua-language-server
  - kcat
  - findutils
  - netcat
  - onefetch
  - openapi-generator
  - openvpn
  - pyenv
  - rust
  - shellcheck
  - stern
  - terraform-ls
  - watch
  - fontconfig
  - sqlc
  - groovy
  

homebrew_cask_apps:
  - bitwarden
  - chromedriver
  - discord
  - drawio
  - firefox
  - gitkraken
  - google-chrome
  - handbrake
  - intellij-idea-ce
  - iterm2
  - leapp
  - licecap
  - macfuse
  - macpass
  - notunes
  - obsidian
  - pgadmin4
  - postman
  - rancher
  - session-manager-plugin
  - skype
  - slack
  - spotify
  - visual-studio-code
  - wezterm
  - wireshark
  - homebrew/cask-fonts/font-hack-nerd-font

    
#requires one to have apple id in advance - I never have my own
mas_installed_apps: []
  # - { id: 993841014, name: "CopyLess 2 - Clipboard Manager" }

composer_packages: []

gem_packages: []

#TODO get all the lsp servers using lsp-lazy instead in nvim
npm_packages:
  - name: webpack
    # state: latest
  - name: bash-language-server
    # state: present
    # version: "server-4.6.1"
  - name: pyright
    # state: present
    # version: "1.1.292"
  - name: yaml-language-server
  - name: vscode-langservers-extracted


pip_packages:
  - pynvim
  - botocore
  - awscli
  #TODO fix - aws_completer
  - pipenv

configure_dock: true
dockitems_remove: 
  - "Contacts"
  - "Safari"
  - "Launchpad"
  - "Photos"
  - "FaceTime"
  - "Freeform"
  - "TV"
  - "Music"
  - "Maps"
  - "Podcasts"
  - "News"
  - "App Store"

dockitems_persist:
  - name: "iTerm"
    path: "/Applications/iTerm.app/"
    pos: 2
  - name: "Google Chrome"
    path: "/Applications/Google Chrome.app/"
    pos: 3
  - name: "Slack"
    path: "/Applications/Slack.app/"
    pos: 4
