
#some good options in his config, but not to my tastes
configure_dotfiles: false
configure_terminal: false
configure_osx: false

configure_sudoers: false


homebrew_installed_packages:
  - autoconf
  - bash-completion
  - bat
  - doxygen
  - gettext
  - gifsicle
  - git
  - github/gh/gh
  - warrensbox/tap/tfswitch
  - go
  - gpg
  - fzf
  - httpie
  - iperf
  - libevent
  - sqlite
  - mcrypt
  - nmap
  - node
  - neofetch
  - nvm
  - ssh-copy-id
  - cowsay
  - readline
  - openssl
  - pv
  - telnet
  - wget
  - wrk
  - coreutils 
  - findutils 
  - gnu-tar 
  - gnu-sed 
  - gawk 
  - gnutls 
  - gnu-indent 
  - gnu-getopt 
  - grep
  - neovim
  - terraform

homebrew_cask_apps:
  - chromedriver
  - firefox
  - google-chrome
    # TODO: currently doesnt work - homebrew/cask-fonts/font-hack-nerd-font-mono
  - handbrake
  - licecap
  - slack
  - iterm2


    
  #requires one to have apple id in advance - I never have my own
mas_installed_apps: []
  # - { id: 993841014, name: "CopyLess 2 - Clipboard Manager" }

composer_packages: []

gem_packages: []

npm_packages:
  - name: webpack

pip_packages:
  - pynvim
  - botocore
  - awscli
  - aws_completer
  - pipenv

configure_dock: true
dockitems_remove: 
  - "Contacts"
  - "Safari"
  - "Launchpad"
  - "Photos"
  - "FaceTime"
  - "Freeform"
  - "TV"
  - "Music"
  - "Maps"
  - "Podcasts"
  - "News"
  - "App Store"

dockitems_persist:
  - name: "iTerm"
    path: "/Applications/iTerm.app/"
    pos: 2
  - name: "Google Chrome"
    path: "/Applications/Google Chrome.app/"
    pos: 3
  - name: "Slack"
    path: "/Applications/Slack.app/"
    pos: 4
