#some good options in his config, but not to my tastes
# configure_terminal: false

configure_dotfiles: true
dotfiles_repo: https://github.com/gfcroft/dotfiles.git
dotfiles_repo_accept_hostkey: true
dotfiles_repo_local_destination: ~/repos/config/dotfiles

# just (mac) osx configuring script for now
dotfiles_files:
  - .osx

configure_osx: true
osx_script: "~/.osx --no-restart"



#TODO some way of disabling system shortcuts that get in the way such as the ctrl-space shortcut in system prefs
#TODO some way of pinning packages, and ideally of stating version of packages we want (though that is tricky - brew seems to be a bit rubbish when it comes to getting old versions of packages)

configure_sudoers: false

homebrew_taps:
  - warrensbox/tap
  - gfcroft/homebrew-tap

#### additional manual steps
# bash - have to add to list of system shells, then chsh:
#  don't forget to echo "$(brew --prefix)/bin/bash" | sudo tee -a /etc/shells ; then chsh -s "$(brew --prefix)/bin/bash"

homebrew_installed_packages:
  - act
  - autoconf
  - bash 
  - bash-completion@2
  - bat
  - doxygen
  - dockutil
  - gettext
  - gifsicle
  - git
  - gh
  - tfswitch
  - go
  - gpg
  - fzf
  - httpie
  - iperf
  - libevent
  - sqlite
  - nmap
  - node
  - neofetch
  - nvm
  - ssh-copy-id
  - cowsay
  - readline
  - openssl
  - pv
  - telnet
  - wget
  - wrk
  - coreutils 
  - findutils 
  - gnu-tar 
  - gnu-sed 
  - gawk 
  - gnutls 
  - gnu-indent 
  - gnu-getopt 
  - grep
  - neovim
  - mtr
  - ripgrep
  - the_silver_searcher
  - speedtest-cli
  - leapp-cli
  - kubectx
  - tree
  - consul
  - yarn
  - yarn-completion
  - vault
  - helm
  - yamllint
  - jq
  - k9s
  - figlet
  - lua-language-server
  - kcat
  - findutils
  - netcat
  - onefetch
  - openapi-generator
  - openvpn
  - pyenv
  - rust
  - shellcheck
  - stern
  - terraform-ls
  - watch
  - fontconfig
  - sqlc
  - groovy
  - simple-pass
  

homebrew_cask_apps:
  - bitwarden
  - chromedriver
  - discord
  - drawio
  - firefox
  - google-chrome
  - handbrake
  - intellij-idea-ce
  - iterm2
  - leapp
  - licecap
  - macfuse
  - macpass
  - notunes
  - obsidian
  - pgadmin4
  - postman
  - rancher
  - session-manager-plugin
  - skype
  - slack
  - spotify
  - visual-studio-code
  - wezterm
  - wireshark
  - homebrew/cask-fonts/font-hack-nerd-font

    
#requires one to have apple id in advance - login to app store first!
# bash -c "mas list"
mas_installed_apps: 
  - { id: 993841014, name: "CopyLess 2 - Clipboard Manager" }
  - { id: 1295203466  , name: "Microsoft Remote Desktop" }
  - { id: 823766827   , name: "OneDrive" }
  - { id: 302584613   , name: "Kindle" }


composer_packages: []

gem_packages: []

#TODO get all the lsp servers using lsp-lazy instead in nvim
npm_packages:
  - name: webpack
    # state: latest
  - name: bash-language-server
    # state: present
    # version: "server-4.6.1"
  - name: pyright
    # state: present
    # version: "1.1.292"
  - name: yaml-language-server
  - name: vscode-langservers-extracted


# TODO need to implement pipx to get around new PEP 668 constraint that breaks this
# for now, pipx them 
# pip_packages:
#   - name: pynvim
#     state: present
#   - name: botocore
#     state: present
#   - name: awscli
#     state: present
#   - name: pipenv
#     state: present

configure_dock: true
dockitems_remove: 
  - "Contacts"
  - "Safari"
  - "Launchpad"
  - "Photos"
  - "FaceTime"
  - "Freeform"
  - "TV"
  - "Music"
  - "Maps"
  - "Podcasts"
  - "News"
  - "App Store"

# sometimes the ordering works, sometimes it doesn't ?!
dockitems_persist:
  - name: "Mail"
    path: "/System/Applications/Mail.app"
    pos: 2
  - name: "iTerm"
    path: "/Applications/iTerm.app/"
    pos: 3
  - name: "Google Chrome"
    path: "/Applications/Google Chrome.app/"
    pos: 4
  - name: "Slack"
    path: "/Applications/Slack.app/"
    pos: 5
  - name: "Reminders"
    path: "/Applications/Reminders.app/"
    pos: 6
  - name: "Notes"
    path: "/Applications/Notes.app/"
    pos: 7
  - name: "Calendar"
    path: "/Applications/Calendar.app/"
    pos: 8
  - name: "System Settings"
    path: "/Applications/System Settings.app/"
    pos: 9
  - name: "Messages"
    path: "/Applications/Messages.app/"
    pos: 10
